# Generated by Django 5.2.12 on 2026-03-10 00:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0002_libro_imagen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cart_id", models.UUIDField(db_index=True, unique=True)),
                ("guest_token", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("status", models.CharField(choices=[("completed", "Completed"), ("refunded", "Refunded"), ("cancelled", "Cancelled")], db_index=True, default="completed", max_length=20)),
                ("currency", models.CharField(default="CLP", max_length=3)),
                ("subtotal_amount", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("discount_amount", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("items_count", models.PositiveIntegerField(default=0)),
                ("total_quantity", models.PositiveIntegerField(default=0)),
                ("sold_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ventas", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-sold_at",)},
        ),
        migrations.CreateModel(
            name="VentaItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("libro_nombre", models.CharField(max_length=255)),
                ("autor_nombre", models.CharField(blank=True, max_length=255)),
                ("editorial_nombre", models.CharField(blank=True, max_length=255)),
                ("genero_nombre", models.CharField(blank=True, max_length=120)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("idioma", models.CharField(blank=True, max_length=60)),
                ("unit_price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("quantity", models.PositiveIntegerField()),
                ("subtotal", models.DecimalField(decimal_places=0, max_digits=12)),
                ("sold_at", models.DateTimeField(db_index=True)),
                ("metadata_snapshot", models.JSONField(blank=True, default=dict)),
                ("libro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="productos.libro")),
                ("venta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="ventas.venta")),
            ],
            options={"ordering": ("id",)},
        ),
    ]
