# Generated by Django 5.2.12 on 2026-03-09 00:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
