# Generated by Django 5.2.12 on 2026-04-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_repair_legacy_ventaitem_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='venta',
            name='contact_first_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='venta',
            name='contact_last_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='venta',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='venta',
            name='despachado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='venta',
            name='shipping_country',
            field=models.CharField(blank=True, default='Chile', max_length=80),
        ),
        migrations.AddField(
            model_name='venta',
            name='shipping_postal_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='venta',
            name='shipping_region',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
