# Generated by Django 5.2.12 on 2026-04-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_contact_email_venta_contact_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDespacho',
            fields=[
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ventas.venta',),
        ),
    ]
