# Generated by Django 5.2.12 on 2026-04-26 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('resumen', models.CharField(blank=True, max_length=320)),
                ('contenido', models.TextField()),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='blog/posts/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado')], db_index=True, default='DRAFT', max_length=10)),
                ('publicado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publicado_en', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='blog/posts/gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='blog.blogpost')),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'publicado_en'], name='blog_blogpo_status_b8a823_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostimage',
            index=models.Index(fields=['post', 'orden'], name='blog_blogpo_post_id_a23ee5_idx'),
        ),
    ]
