# Generated by Django 5.2.12 on 2026-03-10 00:00

import checkout.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0002_libro_imagen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("guest_token", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("currency", models.CharField(default="CLP", max_length=3)),
                ("status", models.CharField(choices=[("active", "Active"), ("converted", "Converted"), ("expired", "Expired"), ("abandoned", "Abandoned")], db_index=True, default="active", max_length=20)),
                ("subtotal_amount", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("discount_amount", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("expires_at", models.DateTimeField(db_index=True, default=checkout.models.default_cart_expiry)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="carts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-updated_at",)},
        ),
        migrations.CreateModel(
            name="CartDiscount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, max_length=64)),
                ("type", models.CharField(choices=[("coupon", "Coupon"), ("percent", "Percent"), ("fixed", "Fixed"), ("qty_promo", "Quantity promo")], max_length=20)),
                ("value", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("amount", models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=12)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="discounts", to="checkout.cart")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_snapshot", models.DecimalField(decimal_places=0, max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=0, max_digits=12)),
                ("metadata_snapshot", models.JSONField(blank=True, default=dict)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("book", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="productos.libro")),
                ("cart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="checkout.cart")),
            ],
            options={"ordering": ("id",), "unique_together": {("cart", "book")}},
        ),
        migrations.CreateModel(
            name="CartOperationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(default=checkout.models.default_cart_expiry)),
                ("cart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operation_logs", to="checkout.cart")),
            ],
            options={"ordering": ("-created_at",), "unique_together": {("cart", "operation", "idempotency_key")}},
        ),
        migrations.CreateModel(
            name="CartTaxLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("taxable_base", models.DecimalField(decimal_places=0, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tax_lines", to="checkout.cart")),
            ],
            options={"ordering": ("name",), "unique_together": {("cart", "name")}},
        ),
    ]
