# Generated by Django 5.2.12 on 2026-03-09 00:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_cart_unique_active_cart_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartdiscount',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartdiscount',
            name='value',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carttaxline',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carttaxline',
            name='taxable_base',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
