# Generated by Django 5.2.12 on 2026-04-13 20:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type', models.CharField(choices=[('coupon', 'Coupon'), ('percent', 'Percent'), ('fixed', 'Fixed'), ('qty_promo', 'Quantity promo')], max_length=20)),
                ('value', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('min_subtotal_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='cartdiscount',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_discounts', to='checkout.discountcoupon'),
        ),
    ]
