# Generated by Django 5.2.12 on 2026-03-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0003_alter_libro_precio_alter_libro_precio_referencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("book", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="inventory_item", serialize=False, to="productos.libro")),
                ("stock", models.PositiveIntegerField(default=0)),
                ("reserved_stock", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("book",)},
        ),
    ]
