# Generated by Django 5.2.12 on 2026-03-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_comuna_region_usuario_comuna_comuna_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.region'),
        ),
    ]
