"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_DEFAULT_SECRET_KEY = "django-insecure-$@wldffpm4$ppt4ap5hm_b&s-py8m3$s)09%4@7g-c!frfb=m9"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", _DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"
IS_PRODUCTION = os.getenv("DJANGO_ENV", "development").strip().lower() == "production"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,.onrender.com").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',
    'django_filters',
    'usuarios',
    'productos',
    'checkout',
    'ventas',
    'despachos',
    'inventory',
    'orders',
    'shipping',
    'payments',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'payments.middleware.PaymentsExceptionRescueMiddleware',
    'payments.middleware.ApiExceptionDiagnosticMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL") or os.getenv("DB_URL")
if DATABASE_URL and not os.getenv("DATABASE_URL"):
    # Compatibilidad heredada: algunos entornos usan DB_URL.
    # Normalizamos para que dj-database-url lea siempre DATABASE_URL.
    os.environ["DATABASE_URL"] = DATABASE_URL

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=DATABASE_URL.startswith("postgresql://") if DATABASE_URL else False,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "usuarios.Usuario"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "False").lower() == "true"
CORS_ALLOW_CREDENTIALS = os.getenv("CORS_ALLOW_CREDENTIALS", "True").lower() == "true"

_cors_allowed_origins = os.getenv("CORS_ALLOWED_ORIGINS", "")
if _cors_allowed_origins:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_allowed_origins.split(",") if origin.strip()]
elif not IS_PRODUCTION:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5174",
        "http://127.0.0.1:5174",
        "http://localhost:4173",
        "http://127.0.0.1:4173",
    ]

_csrf_trusted_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if _csrf_trusted_origins:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_trusted_origins.split(",") if origin.strip()]
elif not IS_PRODUCTION:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5174",
        "http://127.0.0.1:5174",
        "http://localhost:4173",
        "http://127.0.0.1:4173",
    ]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "idempotency-key",
    "x-guest-token",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.StandardResultsSetPagination',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv("DRF_THROTTLE_ANON", "60/min"),
        'user': os.getenv("DRF_THROTTLE_USER", "300/min"),
        'auth_login': os.getenv("DRF_THROTTLE_AUTH_LOGIN", "10/min"),
        'auth_refresh': os.getenv("DRF_THROTTLE_AUTH_REFRESH", "30/min"),
        'auth_logout': os.getenv("DRF_THROTTLE_AUTH_LOGOUT", "30/min"),
        'auth_csrf': os.getenv("DRF_THROTTLE_AUTH_CSRF", "120/min"),
        'catalog_public': os.getenv("DRF_THROTTLE_CATALOG_PUBLIC", "60/min"),
        'checkout_read': os.getenv("DRF_THROTTLE_CHECKOUT_READ", "30/min"),
        'checkout_write': os.getenv("DRF_THROTTLE_CHECKOUT_WRITE", "20/min"),
        'payments_user': os.getenv("DRF_THROTTLE_PAYMENTS_USER", "20/min"),
        'payments_commit_public': os.getenv("DRF_THROTTLE_PAYMENTS_COMMIT_PUBLIC", "10/min"),
        'payments_webhook_public': os.getenv("DRF_THROTTLE_PAYMENTS_WEBHOOK_PUBLIC", "30/min"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_TOKEN_MINUTES", "15"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_TOKEN_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": os.getenv("JWT_ROTATE_REFRESH_TOKENS", "true").lower() == "true",
    "BLACKLIST_AFTER_ROTATION": os.getenv("JWT_BLACKLIST_AFTER_ROTATION", "true").lower() == "true",
}

AUTH_REFRESH_COOKIE_NAME = os.getenv("AUTH_REFRESH_COOKIE_NAME", "refresh_token")
AUTH_REFRESH_COOKIE_SECURE = os.getenv(
    "AUTH_REFRESH_COOKIE_SECURE",
    "true" if IS_PRODUCTION else "false",
).lower() == "true"
AUTH_REFRESH_COOKIE_SAMESITE = os.getenv(
    "AUTH_REFRESH_COOKIE_SAMESITE",
    "None" if IS_PRODUCTION else "Lax",
)
AUTH_REFRESH_COOKIE_PATH = os.getenv("AUTH_REFRESH_COOKIE_PATH", "/auth/jwt/")

# Los precios del catálogo ya incluyen IVA, por lo que no se debe recargar en checkout.
CHECKOUT_APPLY_TAX = False
CHECKOUT_TAX_RATE = os.getenv("CHECKOUT_TAX_RATE", "0.19")
WEBPAY_COMMERCE_CODE = os.getenv("WEBPAY_COMMERCE_CODE", "597055555532")
WEBPAY_API_KEY = os.getenv("WEBPAY_API_KEY", "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C")
WEBPAY_ENVIRONMENT = os.getenv("WEBPAY_ENVIRONMENT", "").strip().upper()
WEBPAY_RETURN_URL = os.getenv("WEBPAY_RETURN_URL", "http://localhost:8000/payments/webpay/return/")
WEBPAY_FRONTEND_RESULT_URL = os.getenv("WEBPAY_FRONTEND_RESULT_URL", "http://localhost:5173/checkout/resultado")
PAYMENTS_WEBHOOK_SECRET = os.getenv("PAYMENTS_WEBHOOK_SECRET", "")

if IS_PRODUCTION and SECRET_KEY == _DEFAULT_SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY debe configurarse en produccion.")

_default_webpay_code = "597055555532"
_default_webpay_key = "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
if IS_PRODUCTION and WEBPAY_ENVIRONMENT == "LIVE" and (
    WEBPAY_COMMERCE_CODE == _default_webpay_code or WEBPAY_API_KEY == _default_webpay_key
):
    raise ImproperlyConfigured(
        "Las credenciales de Webpay LIVE deben configurarse en produccion."
    )

if IS_PRODUCTION and not PAYMENTS_WEBHOOK_SECRET:
    raise ImproperlyConfigured("PAYMENTS_WEBHOOK_SECRET debe configurarse en produccion.")

CSRF_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SAMESITE = os.getenv(
    "CSRF_COOKIE_SAMESITE",
    "None" if IS_PRODUCTION else "Lax",
)
SESSION_COOKIE_SAMESITE = os.getenv(
    "SESSION_COOKIE_SAMESITE",
    "None" if IS_PRODUCTION else "Lax",
)
SECURE_SSL_REDIRECT = os.getenv(
    "SECURE_SSL_REDIRECT",
    "true" if IS_PRODUCTION else "false",
).lower() == "true"
SECURE_HSTS_SECONDS = int(
    os.getenv("SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION else "0")
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

DJOSER = {
    "LOGIN_FIELD": "email",
    "SEND_ACTIVATION_EMAIL": True,
    "SEND_CONFIRMATION_EMAIL": True,
    "USER_CREATE_PASSWORD_RETYPE": True,
    "SET_PASSWORD_RETYPE": True,
    "SERIALIZERS": {
        "user_create": "usuarios.serializers.DjoserUserCreateSerializer",
        "user": "usuarios.serializers.DjoserUserSerializer",
        "current_user": "usuarios.serializers.DjoserUserSerializer",
    },
    "PASSWORD_RESET_CONFIRM_URL": os.getenv(
        "PASSWORD_RESET_CONFIRM_URL",
        "password/reset/confirm/{uid}/{token}",
    ),
    "ACTIVATION_URL": os.getenv("ACTIVATION_URL", "activate/{uid}/{token}"),
    "EMAIL_FRONTEND_DOMAIN": os.getenv("EMAIL_FRONTEND_DOMAIN"),
    "EMAIL_FRONTEND_PROTOCOL": os.getenv("EMAIL_FRONTEND_PROTOCOL"),
    "EMAIL_FRONTEND_SITE_NAME": os.getenv("EMAIL_FRONTEND_SITE_NAME"),
}

JAZZMIN_SETTINGS = {
    "site_title": "Esperpentia Admin",
    "site_header": "Esperpentia Admin",
    "site_brand": "Esperpentia Admin",
    "welcome_sign": "Bienvenido a Esperpentia Admin",
    "copyright": "Esperpentia",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "productos.Libro": "fas fa-book-open",
        "productos.Obra": "fas fa-pen-nib",
        "productos.género": "fas fa-tags",
        "productos.Autor": "fas fa-user-edit",
        "productos.Editorial": "fas fa-building",
        "despachos.Despacho": "fas fa-truck",
    },
    "order_with_respect_to": ["productos", "despachos", "ventas"],
    "custom_links": {
        "productos": [
            {
                "name": "Ir al catálogo público",
                "url": "/catalog/libros/",
                "new_window": True,
            },
        ]
    },
}

