# Generated by Django 5.2.12 on 2026-04-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0007_ventadespacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido por despachar',
                'verbose_name_plural': 'Despachos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ventas.venta',),
        ),
    ]
