# Generated by Django 5.2.12 on 2026-03-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("biografia", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("nombre",)},
        ),
        migrations.CreateModel(
            name="Editorial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("sitio_web", models.URLField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("nombre",)},
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("nombre",)},
        ),
        migrations.CreateModel(
            name="Obra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("descripcion_corta", models.CharField(blank=True, max_length=300)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("autor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="obras", to="productos.autor")),
                ("genero", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="obras", to="productos.genero")),
            ],
            options={"ordering": ("titulo",), "unique_together": {("titulo", "autor")}},
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("imagen", models.ImageField(blank=True, null=True, upload_to="productos/")),
                ("descripcion", models.TextField(blank=True)),
                ("descripcion_corta", models.CharField(blank=True, max_length=300)),
                ("precio", models.DecimalField(decimal_places=0, max_digits=12)),
                ("precio_referencia", models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ("moneda", models.CharField(choices=[("CLP", "Peso chileno"), ("USD", "Dolar")], default="CLP", max_length=3)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("gestionar_stock", models.BooleanField(default=True)),
                ("peso_kg", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("alto_cm", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("ancho_cm", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("largo_cm", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("destacado", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("tipo_tapa", models.CharField(choices=[("DURA", "Tapa dura"), ("BLANDA", "Tapa blanda")], max_length=10)),
                ("cantidad_paginas", models.PositiveIntegerField()),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("idioma", models.CharField(default="es", max_length=60)),
                ("anio_publicacion", models.PositiveIntegerField(blank=True, null=True)),
                ("editorial", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="libros", to="productos.editorial")),
                ("obra", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="libros", to="productos.obra")),
            ],
            options={"ordering": ("-creado_en",), "abstract": False},
        ),
    ]
