# Generated by Django 5.2.12 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_libro_precio_alter_libro_precio_referencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="libros/%Y/%m/"),
        ),
    ]
