# Generated by Django 5.2.12 on 2026-03-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_libro_imagen_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='productos.editorial'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='productos.obra'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='productos.autor'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='productos.genero'),
        ),
    ]
