# Generated by Django 5.2.12 on 2026-04-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_repair_legacy_catalog_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autores/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='editorial',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='editoriales/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
