# Generated by Django 5.2.12 on 2026-04-13 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_sale_alter_order_user'),
        ('ventas', '0003_alter_venta_user_alter_ventaitem_libro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='ventas.venta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
