# Generated by Django 5.2.12 on 2026-05-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_discountcoupon_cartdiscount_coupon'),
        ('orders', '0003_alter_order_sale_alter_order_user'),
        ('ventas', '0007_ventadespacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='checkout.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_contact_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='ventas.venta'),
        ),
    ]
